name: ⭐ Feature request
description: Create a new feature request.
title: 'feat: <title>'
labels: [feature request]
body:
  - type: markdown
    attributes:
      value: |
        # ReVanced Manager feature request

        Please check for existing feature requests [here](https://github.com/revanced/revanced-manager/labels/bug) before creating a new one.
  - type: textarea
    attributes:
      label: Feature description
      description: Describe your feature in detail.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: Explain why the lack of it is a problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: In case there is something else you want to add.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you don't follow the checklist below!
      options:
        - label: This request is not a duplicate of an existing issue.
          required: true
        - label: I have chosen an appropriate title.
          required: true
        - label: All requested information has been provided properly.
          required: true
        - label: The issue is solely related to the ReVanced Manager
          required: true
